services:
  kafka:
    image: confluentinc/cp-kafka:latest
    container_name: kafka
    hostname: kafka
    ports:
      - "19092:9092"
    volumes:
      - ./private/:/etc/kafka
      - ./users:/tmp/users
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: BROKER:SSL,CONTROLLER:PLAINTEXT,HOST:SSL
      KAFKA_LISTENERS: BROKER://kafka:9092,CONTROLLER://kafka:9093,HOST://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: BROKER://kafka:9092,HOST://localhost:19092
      KAFKA_INTER_BROKER_LISTENER_NAME: BROKER
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_AUTHORIZER_CLASS_NAME: org.apache.kafka.metadata.authorizer.StandardAuthorizer
      KAFKA_ALLOW_EVERYONE_IF_NO_ACL_FOUND: "true"
      KAFKA_CONFLUENT_SUPPORT_METRICS_ENABLE: "false"
      KAFKA_SUPER_USERS: User:admin
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_REPLICATOR_Acks: all
      # Настройки ssl
      KAFKA_SSL_KEYSTORE_FILENAME: "kafka.keystore.jks"
      KAFKA_SSL_KEYSTORE_LOCATION: "/etc/kafka/kafka.keystore.jks"
      KAFKA_SSL_KEYSTORE_PASSWORD: "password"
      KAFKA_SSL_TRUSTSTORE_FILENAME: "kafka.truststore.jks"
      KAFKA_SSL_TRUSTSTORE_LOCATION: "/etc/kafka/kafka.truststore.jks"
      KAFKA_SSL_TRUSTSTORE_PASSWORD: "password"
      KAFKA_SSL_KEY_PASSWORD: "password"
      KAFKA_SSL_CLIENT_AUTH: "required"
      KAFKA_SSL_ENDPOINT_IDENTIFICATION_ALGORITHM: ""
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
